name: C CI

on:
  push:
    paths-ignore: 
      - '.github/**'
    tags-ignore:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  build-local:
    name: Build locally
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go environment
      uses: actions/setup-go@v5.0.2
      with:
        go-version: '1.22'
    - name: Build
      run: go build -v .

  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      run: docker build -v -f docker/Dockerfile .