name: Build Docker package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lowercase_owner_name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.actor }}

      - id: lowercase_repo_name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.event.repository.name }}

      - name: Build image
        run: |
          PACKAGE_NAME="ghcr.io/${{ steps.lowercase_owner_name.outputs.lowercase }}/${{ steps.lowercase_repo_name.outputs.lowercase }}"
          docker build -f docker/Dockerfile --tag ${PACKAGE_NAME}:${{ github.event.release.tag_name }} --tag ${PACKAGE_NAME}:latest .
          docker push ${PACKAGE_NAME}:latest

      - name: Delete old package versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ steps.lowercase_repo_name.outputs.lowercase }}
          package-type: 'container'
          min-versions-to-keep: 4
